version: "3"
services:
  web:
    stdin_open: true
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./server:/app